WeiXin/webapp/models.py
import time
from sqlalchemy.databases import mysql
from webapp import db


class Account(db.Model):
    __tablename__ = "wx_account"
    __table_args__ = {
        "useexisting": True,
        'mysql_charset': 'utf8mb4'
    }

    id = db.Column(db.Integer, primary_key=True)
    account_name = db.Column(db.String(50))  # 公众号名称
    account_id = db.Column(db.String(30), unique=True)  # 公众号唯一id
    account_biz = db.Column(db.String(20), unique=True)  # 公众号__biz
    account_id_unique = db.Column(db.String(30), unique=True)  # 公众号唯一id
    account_logo = db.Column(db.String(300), unique=True)  # 公众号头像
    account_desc = db.Column(db.String(300))  # 公众号描述
    account_url = db.Column(db.String(500), unique=True)  # 公众号解析链接

    created = db.Column(db.String(20), default=str(int(time.time())))  # 公众号添加时间

    status = db.Column(db.Integer, default=0)  # 状态0-未运行，1-等待中，2-运行中，3-已暂停
    offset = db.Column(db.Integer, default=0)  # 公众号偏移量
    counts = db.Column(db.Integer, default=0)  # 公众号获取的文章数量
    end = db.Column(db.Boolean, default=False)  # 公众号爬取是否完毕
    fail = db.Column(db.Boolean, default=False)  # 公众号有效性
    update = db.Column(db.String(20), default="1356969600")  # 公众号更新时间

    project_name = db.Column(db.String(50))  # 项目名称
    project_status = db.Column(db.String(50))  # 项目账号是否启用
    articles = db.relationship("Article", backref="wx_account")

    def __repr__(self):
        return "<Account: %s %s %s %s>" % (self.account_name, self.account_id, self.offset, self.end)


class Article(db.Model):
    __tablename__ = "wx_article"
    __table_args__ = {
        "useexisting": True,
        'mysql_charset': 'utf8mb4'
    }

    id = db.Column(db.Integer, primary_key=True)
    article_title = db.Column(db.String(200))
    article_author = db.Column(db.String(50))
    article_crawl_time = db.Column(db.String(20))
    article_publish_time = db.Column(db.String(20))
    article_copy_right = db.Column(db.Boolean)
    article_digest = db.Column(db.String(300))
    article_html = db.Column(mysql.MSMediumText)

    article_content_url = db.Column(db.String(500), unique=True)
    article_cover_url = db.Column(db.String(500))
    article_source_url = db.Column(db.String(500))
    article_fail = db.Column(db.Boolean, default=False)  # 文章有效性
    article_done = db.Column(db.Boolean, default=False)  # 文章内容是否抓取
    article_comment_id = db.Column(db.String(20))
    comment_update = db.Column(db.String(20), default="1356969600")  # 公众号更新时间
    read_like_update = db.Column(db.String(20), default="1356969600")  # 公众号更新时间
    read_count = db.Column(db.Integer, default=0)
    like_count = db.Column(db.Integer, default=0)
    digg_count = db.Column(db.Integer, default=0)
    new_comment_count = db.Column(db.Integer, default=0)
    reward_total_count = db.Column(db.Integer, default=0)
    comment_count = db.Column(db.Integer, default=0)
    comments = db.relationship("Comment", backref="wx_article")
    account_id = db.Column(db.Integer, db.ForeignKey("wx_account.id"))  # 公众号唯一id

    def __repr__(self):
        return "<Title: %r, Publish: %s>" % (
                   self.article_title,
                   time.strftime('%Y-%m-%d', time.localtime(self.article_publish_time)),

               )


class Comment(db.Model):
    __tablename__ = "wx_comment"
    __table_args__ = {
        "useexisting": True,
        'mysql_charset': 'utf8mb4'
    }

    id = db.Column(db.Integer, primary_key=True)

    user_name = db.Column(db.String(50))
    user_logo = db.Column(db.String(300))

    content = db.Column(db.String(800))
    datetime = db.Column(db.String(20))

    content_id = db.Column(db.String(30), unique=True)
    like_count = db.Column(db.Integer)

    article_id = db.Column(db.Integer, db.ForeignKey("wx_article.id"))
    reply_list = db.relationship("CommentReply", backref="wx_comment")


class CommentReply(db.Model):
    __tablename__ = "wx_comment_reply"
    __table_args__ = {
        "useexisting": True,
        'mysql_charset': 'utf8mb4'
    }

    id = db.Column(db.Integer, primary_key=True)
    reply_uin = db.Column(db.String(20))
    reply_to_uin = db.Column(db.String(20))

    reply_content = db.Column(db.String(300))
    reply_like_count = db.Column(db.Integer)

    reply_datetime = db.Column(db.String(20))
    comment_id = db.Column(db.Integer, db.ForeignKey("wx_comment.id"))


if __name__ == '__main__':
    db.create_all()
    # pass

WeiXin/webapp/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://mongoole:mong00le@localhost:3306/weixin_spider?charset=utf8mb4"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
db = SQLAlchemy(app)

app.debug = True
from webapp.wxapp import wx_app as wx_app_blueprint
app.register_blueprint(wx_app_blueprint)

@app.errorhandler(400)
def page_400(error):
    return render_template("400.html"), 400

@app.errorhandler(401)
def page_401(error):
    return render_template("401.html"), 401

@app.errorhandler(403)
def page_403(error):
    return render_template("403.html"), 403

@app.errorhandler(404)
def page_404(error):
    return render_template("404.html"), 404

@app.errorhandler(500)
def page_500(error):
    return render_template("500.html"), 500

@app.errorhandler(503)
def page_503(error):
    return render_template("503.html"), 503

WeiXin/webapp/wxapp/__init__.py
from flask import Blueprint

wx_app = Blueprint("wx_app", __name__, url_prefix="/", template_folder="../templates/weixin/")

from webapp.wxapp import views
from webapp.wxapp import selffilter

if __name__ == "__main__":
    pass

WeiXin/webapp/wxapp/views.py
from . import wx_app
from webapp.models import Account, Article, Comment
from webapp import db

from urllib.request import urlopen

from flask import render_template, request, redirect, url_for, make_response

from api import get_platform_info_from_url


@wx_app.route("/", methods=['GET'])
def wx_index():
    page = int(request.args.to_dict().get("page", 1))
    page_data = Account.query.order_by(
        Account.created.desc()
    ).paginate(page=page, per_page=11)
    return render_template("wx-index.html", page_data=page_data)


@wx_app.route("/add/", methods=["GET"])
def wx_add():
    wx_uri = request.values.to_dict().get("wx_uri")
    wx_info = get_platform_info_from_url(wx_uri)
    print(wx_info)
    account_count = Account.query.filter_by(account_id_unique=wx_info['account_id_unique']).count()
    if account_count == 1:
        return redirect(url_for("wx_app.wx_index"))
    account = Account(**wx_info)
    db.session.add(account)
    db.session.commit()
    return redirect(url_for("wx_app.wx_index"))


@wx_app.route("/account/", methods=["GET"])
def wx_account():
    account_id = int(request.args.to_dict().get("id", 0))
    page = int(request.args.to_dict().get("page", 1))
    if account_id <= 0:
        return redirect(url_for("wx_app.wx_index"))
    account = Account.query.get(account_id)
    articles = Article.query.filter_by(
        account_id=account_id
    ).order_by(
        Article.article_publish_time.desc()
    ).paginate(page=page, per_page=10)
    return render_template("wx-account.html", account=account, articles=articles)


@wx_app.route("/article/", methods=["GET"])
def wx_article():
    article_id = int(request.args.to_dict().get("id", 0))
    article = Article.query.get(article_id)
    comments = Comment.query.filter_by(
        article_id=article_id
    ).all()
    if article_id <= 0:
        return redirect(url_for("wx_app.wx_index"))
    return render_template("wx-article.html", article=article, comments=comments)


@wx_app.route("/operate/", methods=["GET"])
def wx_operate():
    account_id = int(request.args.to_dict().get("id", 0))
    account_count = Account.query.filter_by(id=account_id).count()
    if account_count != 1:
        return redirect(url_for("wx_app.wx_index"))
    account = Account.query.get(account_id)
    operate = request.args.to_dict().get("operate", "")
    if operate in ["0", "1", "2", "3", "4"]:
        account.status = int(operate)
        db.session.add(account)
        db.session.commit()
    return redirect(url_for("wx_app.wx_index"))


@wx_app.route("/wx_article/", methods=["GET"])
def wx_article_iframe():
    article_id = int(request.args.to_dict().get("id", 0))
    if article_id <= 0:
        return ""
    article = Article.query.get(article_id)
    return article.article_html


@wx_app.route("/wx_images/", methods=["GET"])
def wx_images():
    from ssl import _create_unverified_context
    url = request.args.to_dict().get("url", "")
    img = urlopen(url, context=_create_unverified_context())
    resp = make_response(img.read())
    resp.headers['Content-Type'] = 'image/jpg'
    return resp


if __name__ == '__main__':
    pass

WeiXin/webapp/templates/weixin/wx-account.html
{% extends "wx-base.html" %}
{% import "paginator/base-paginator.html" as pg %}

{% block basesearch %}
    {% include "wx-base-search.html" %}
{% endblock %}

{% block contents %}
    <div class="card card-aside">
        <div class="card-body d-flex flex-column">
            <div class="text-center pt-1 ">
                <div class="avatar avatar-md text-center"
                     style="background-image: url('{{ account.account_logo }}')"></div>

            </div>
            <div class="text-center pt-2 ">

                <span class="text-center">{{ account.account_name }}</span>
                <div class="text-muted">
                    <small class="d-block text-center">微信号：{{ account.account_id }}
                        <a href="javascript:void(0)" class="icon" id="copy_id" data-value="{{ account.account_id }}">
                            <i class="fa fa-copy btn-icon"></i>
                        </a>
                    </small>

                </div>
            </div>
            <div class="pt-2 text-center text-gray">
                {{ account.account_desc }}
            </div>
        </div>
    </div>

    <div class="row row-cards row-deck">
        <div class="col-12">
            <div class="card">
                <div class="table-responsive">
                    <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                        <thead>
                        <tr>
                            <th class="text-left">序号</th>
                            <th class="text-left">标题</th>
                            <th class="text-left">作者</th>
                            <th class="text-left">原创</th>
                            <th class="text-center">阅读数</th>
                            <th class="text-center">在看数</th>
                            <th class="text-center">评论数</th>
                            <th class="text-left">发布时间</th>
                            <th class="text-center">信息有无</th>
                            <th class="text-center">爬取状态</th>
                            <th class="text-center">链接</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for article in articles.items %}
                            <tr>
                                <td class="text-left">
                                    <div class="text-muted">{{ article.id }}</div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted" data-value="{{ article.article_title }}">
                                        {% if article.article_done %}
                                            <a href="{{ url_for('wx_app.wx_article', id=article.id) }}" class="icon">
                                                {{ article.article_title|dot_string }}
                                            </a>
                                        {% else %}
                                            <a href="javascript:void(0);" class="icon">
                                                {{ article.article_title|dot_string }}
                                            </a>
                                        {% endif %}
                                    </div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">{{ article.article_author }}</div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">
                                        {% if article.article_copy_right %}
                                            <i class="fa fa-copyright"></i>
                                        {% endif %}
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">{{ article.read_count }}</div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">{{ article.like_count }}</div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">{{ article.new_comment_count }}</div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">{{ article.article_publish_time|timestamp2time }}</div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">
                                        {% if article.article_fail %}
                                            <i class="fe fe-x text-red"></i>
                                        {% else %}
                                            <i class="fe fe-check text-blue"></i>
                                        {% endif %}
                                    </div>
                                </td>
                                <td class="text-center">
                                    {% if article.article_done %}
                                        <a href="{{ url_for('wx_app.wx_article', id=article.id) }}" class="icon">
                                            <i class="fe fe-file-text text-blue"></i>
                                        </a>
                                    {% else %}
                                        <a href="javascript:void(0);" class="icon">
                                            <i class="fe fe-file-text text-red"></i>
                                        </a>
                                    {% endif %}

                                </td>
                                <td class="text-center">
                                    <a href="{{ article.article_content_url }}" class="icon" target="_blank">
                                        <div class="text-muted"><i class="fe fe-link text-blue"></i></div>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block paginator %}
    <div class="float-right">
        {{ pg.page(articles, "wx_app.wx_account", id=account.id) }}
    </div>
{% endblock %}

{% block js %}
    <script>
        requirejs(["jquery"], function ($) {
            $(document).ready(function () {
                $(".nav_home").addClass("active");
                $("#copy_id").click(function () {
                    var copy_id = $(this).attr("data-value");
                    console.log(copy_id);
                    document.execCommand("Copy");
                });
            })
        })
    </script>
{% endblock %}

WeiXin/webapp/templates/weixin/wx-article.html
{% extends "wx-base.html" %}
{% block css %}
{% endblock %}
{% block contents %}
    <div class="row">
        <div class="col-lg-4 order-lg-1 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="text-wrap p-lg-1">
                        <h5 class="text-left">评论信息：</h5>
                        {% for comment in comments %}
                            <div class="card-body">
                                <div class="d-flex align-items-start">
                                    <img class="avatar avatar-md mr-3"
                                         src="{{ comment.user_logo }}">
                                    <div>
                                        <div class="text-muted small">
                                            {{ comment.user_name }}
                                        </div>
                                        <div class="text-left small">
                                            {{ comment.content }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <div class="text-wrap p-lg-1">
                        <div class="page-title text-center p-lg-2">
                            {{ article.article_title }}
                        </div>
                        <div class="small page-item text-center">
                            {{ article.article_author }}
                        </div>
                        <div class="small page-item text-center">
                            {{ article.article_publish_time|timestamp2time }}
                        </div>
                        <div class="page-content">
{#                            {{ article.article_html|data_src|safe }}#}
                            {{ article.article_html|data_src|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        requirejs(["jquery"], function ($) {
            $(document).ready(function () {
                $(".nav_home").addClass("active");
            })
        })
    </script>
{% endblock %}

WeiXin/webapp/templates/weixin/wx-base-modal.html
<div class="w-25 modal fade m-auto mt-md-9 addPage" id="addPage" tabindex="-1" role="dialog" aria-labelledby="addPageLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modelInfo form-fieldset mb-auto">
                <div class="form-group">
                    <label class="form-label">
                        微信名
                        <span class="form-required">*</span>
                    </label>
                    <input type="text" class="form-control" name="wx_name">
                </div>
                <div class="form-group">
                    <label class="form-label">
                        微信号
                        <span class="form-required">*</span>
                    </label>
                    <input type="text" class="form-control" name="wx_id">
                </div>
                <div class="form-group">
                    <label class="form-label">
                        标识码
                        <span class="form-required">*</span>
                    </label>
                    <input type="text" class="form-control" name="wx_biz">
                </div>
                <button class="btn btn-default btn-block" data-dismiss="modal">退出</button>
                <button class="btn btn-primary btn-block" id="wx_add">确定</button>

        </div>
    </div>
</div>

WeiXin/webapp/templates/weixin/wx-base-nav.html
<div class="col-lg order-lg-first">
    <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
        <li class="nav-item">
            <a href="/" class="nav-link nav_home">
                <i class="fe fe-home"></i>Wechat Office Account
            </a>
        </li>
    </ul>
</div>

WeiXin/webapp/templates/weixin/wx-base-search.html
<div class="col-lg-3 ml-auto">
    <form class="input-icon my-3 my-lg-0">
        <input type="search" class="form-control header-search" placeholder="Search&hellip;"
               tabindex="1">
        <div class="input-icon-addon">
            <i class="fe fe-search"></i>
        </div>
    </form>
</div>

WeiXin/webapp/templates/weixin/wx-footer.html
<footer class="footer">
    <div class="container">
        <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
            Copyright © 2019-2021  WeChat Office Account.
        </div>
    </div>
</footer>

WeiXin/webapp/templates/weixin/wx-index.html
{% extends "wx-base.html" %}
{% import "paginator/base-paginator.html" as pg %}

{% block basesearch %}
    {% include "wx-base-search.html" %}
{% endblock %}
{% block contents %}
    <script>
        function clear_input() {
            document.getElementsByName('wx_uri')[0].classList.remove("is-invalid");
        }

        function re_check(reg, string) {
            return reg.test(string)
        }

        function url_check() {
            var wx_uri = document.getElementsByName('wx_uri')[0];
            wx_uri.value = wx_uri.value.trim();
            if (re_check(/^https?:\/\/mp\.weixin\.qq\.com\/.+/, wx_uri.value)) {
                return true;
            }
            wx_uri.classList.add('is-invalid');
            return false;
        }
    </script>
    <div class="row row-cards row-deck">
        <div class="col-12">
            <form action="{{ url_for('wx_app.wx_add') }}" method="get" class="form-group"
                  onsubmit="return url_check();">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="输入公众号文章链接进行提取" name="wx_uri"
                           onclick="clear_input()">
                    <span class="input-group-btn">
                        <button class="btn btn-outline-primary" type="submit">
                            <i class="fe fe-plus small"></i>
                            添加公众号
                        </button>
                    </span>
                </div>
            </form>

            <div class="card">
                <div class="table-responsive">
                    <table class="table table-hover table-outline table-vcenter text-nowrap card-table table-condensed">
                        <thead>
                        <tr>
                            <th class="text-left">ID</th>
                            <th class="text-left"><i class="fa fa-weixin"></i></th>
                            <th class="text-left">微信名称</th>
                            <th class="text-left">微信号</th>
                            <!--th class="text-left">微信ID</th-->
                            <!--th-- class="text-left">识别码</th-->
                            <th class="text-left">总量</th>
                            <th class="text-center">更新时间</th>
                            <th class="text-left">数据状态</th>
                            <th class="text-center">运行状态</th>
                            <th class="text-center">所属项目</th>
                            <th class="text-center">控制</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for item in page_data.items %}
                            <tr>
                                <td class="text-left">
                                    <div class=" small">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.id }}
                                        </a>
                                    </div>
                                </td>
                                <td class="text-left">
                                    <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                        <div class="avatar d-block"
                                             style="background-image: url('{{ item.account_logo }}')">
                                            <span class="avatar-status bg-green"></span>
                                        </div>
                                    </a>
                                </td>
                                <td class="text-left">
                                    <div class=" small">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.account_name }}
                                        </a>
                                    </div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.account_id }}
                                        </a>
                                    </div>
                                </td>
                                <!--td class="text-left">
                                    <div class="text-muted">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.account_id_unique }}
                                        </a>
                                    </div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.account_biz|biz_to_short }}
                                        </a>
                                    </div>
                                </td-->
                                <td class="text-left">
                                    <div class="text-muted">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.counts }}
                                        </a>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">{{ item.update|timestamp2time }}</div>
                                </td>
                                <td class="text-left">
                                    <div class="text-muted">
                                        {% if item.status in [1, 2] %}
                                            同步中
                                        {% elif item.end %}
                                            已同步
                                        {% else %}
                                            未同步
                                        {% endif %}
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="text-muted">
                                        {% if item.status == 0 %}
                                            未运行
                                        {% elif item.status == 1 %}
                                            等待中
                                        {% elif item.status == 2 %}
                                            运行中
                                        {% elif item.status == 3 %}
                                            已暂停
                                        {% else %}
                                            异常
                                        {% endif %}
                                        <!--
                                        <i class="fa fa-play text-blue"></i>
                                        <i class="fa fa-pause text-blue"></i>
                                        <i class="fa fa-stop text-blue"></i>
                                        <i class="fa fa-stop text-red"></i>
                                        -->
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class=" small">
                                        <a href="{{ url_for('wx_app.wx_account', id=item.id) }}" class="icon">
                                            {{ item.project_name }}
                                        </a>
                                    </div>
                                </td>
                                <td class="text-center">
                                    {% if item.status in [0, 3] %}
                                        <a href="{{ url_for('wx_app.wx_operate', operate=1, id=item.id) }}"
                                           class="btn btn-link, btn-sm">
                                            启动
                                        </a>
                                    {% elif item.status in [1, 2] %}
                                        <a href="{{ url_for('wx_app.wx_operate', operate=0, id=item.id) }}"
                                           class="btn btn-link, btn-sm">
                                            停止
                                        </a>
                                    {% else %}
                                        <a href="javascript:void(0);" class="btn btn-link btn-sm">
                                            异常
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block paginator %}
    <div class="float-right">
        {{ pg.page(page_data, "wx_app.wx_index") }}
    </div>
{% endblock %}

{% block js %}
    <script>
        requirejs(["jquery"], function ($) {
            $(document).ready(function () {
                $(".nav_home").addClass("active");
            })
        })
    </script>
{% endblock %}